camunda.bpm.client:
  base-url: http://localhost:8080/engine-rest # The URL pointing to the Camunda Platform Runtime REST API
  #async-response-timeout: 500 # Defines the maximum duration of the long-polling request
  disable-backoff-strategy: true
  worker-id: generic-directus-worker # Identifies the worker towards the Engine

directus:
  items-base-url: http://XXXX:DDDD/items/
  access-token: Bearer XXXX